import { IsJWT } from 'class-validator';

export class VerifyEmailDto {
  // Signed JWT generated by UsersService.deliverEmailVerification.
  // Payload shape: { sub: <userId>, purpose: 'email_verify', email: <address> }.
  @IsJWT()
  token!: string;
}
