import { IsJWT } from 'class-validator';

export class VerifyEmailDto {
  // Signed JWT generated by UsersService.sendEmailVerificationLink.
  // Payload shape: { sub: <userId>, purpose: 'email_verify' }.
  @IsJWT()
  token!: string;
}
