# syntax=docker/dockerfile:1

FROM node:24-alpine AS base
WORKDIR /app

FROM base AS deps
# openssl: required by Prisma's schema engine during `migrate deploy`.
# libc6-compat: shim for npm packages that ship glibc-linked prebuilds.
RUN apk add --no-cache libc6-compat openssl
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Build stage keeps the FULL dev toolchain (prisma CLI, nest CLI). It is
# used directly as the `migrate` service's image (docs/<env>/docker-compose.yml,
# `target: build`, runs `yarn prisma:deploy`), so it must retain devDeps —
# do NOT prune here.
#
# GIT_SHA is embedded in the RUN command so its value participates in the
# build cache key: every commit produces a unique instruction and forces a
# fresh `yarn build`. Without it BuildKit can serve a stale `dist/` across
# commits whose source COPY is content-equivalent (e.g. reverts/cherry-picks).
FROM deps AS build
ARG GIT_SHA=unknown
COPY . .
RUN : "git_sha=${GIT_SHA}" \
 && yarn prisma generate \
 && yarn build

# Pruned production dependencies for the runtime image. Separate stage so the
# `build` target above keeps its devDeps. `--ignore-scripts` is safe: bcrypt's
# prebuild already materialized in `deps`, and @prisma/client's postinstall
# would try to regenerate against a missing schema here — the generated client
# is copied from the `build` stage instead (see below).
FROM deps AS prod-deps
RUN yarn install --production --frozen-lockfile --ignore-scripts

FROM base AS runtime
ENV NODE_ENV=production
# Commit hash baked into the running container (e.g. for a /health/version
# endpoint). `unknown` when the build context didn't pass it (local builds).
ARG GIT_SHA=unknown
ENV GIT_SHA=${GIT_SHA}
# tini for proper PID-1 signal handling. Strip npm/npx/corepack — we run
# `node dist/main.js` directly, and the bundled npm ships a vulnerable
# picomatch (+ ~15MB) that image scanners flag even though our yarn.lock
# controls the app's real dependency tree.
RUN apk add --no-cache openssl tini \
 && rm -rf /usr/local/lib/node_modules/npm \
           /usr/local/lib/node_modules/corepack \
           /usr/local/bin/npm \
           /usr/local/bin/npx \
           /usr/local/bin/corepack \
 && addgroup -S app && adduser -S app -G app
COPY --from=prod-deps --chown=app:app /app/node_modules         ./node_modules
# .prisma/client is generated by `yarn prisma generate` in the build stage;
# prod-deps (installed with --ignore-scripts) lacks it, so copy it over —
# otherwise `require('@prisma/client')` fails at boot with
# "Cannot find module '.prisma/client/default'".
COPY --from=build     --chown=app:app /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=build     --chown=app:app /app/dist                 ./dist
COPY --from=build     --chown=app:app /app/package.json         ./package.json
USER app
EXPOSE 3000
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "dist/main.js"]
